### PR TITLE
Fix jenkins-infra#201 can't jump to English site

### PR DESCRIPTION
**Pull request by shenxianpeng**
#201 passed my test. now click English button can jump to English site https://jenkins.io/, would like your review, Thank you!

@jenkins-infra/chinese-localization-sig

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
I just tested it. Once I clicked the menu of English in the browse which settings the language as Chinese, then the address will be jenkins.io redirect to jenkins.io/zh.

But it's ok under the English browse environment.

**Comment by shenxianpeng** [comment]
tested on another machine's browser, I can't reproduce this issue #201
on my laptop, I can reproduce this problem. open https://jenkins.io always automatically jumps to https://jenkins.io/zh/, so click 中文->English can't jump back to English site

**Comment by shenxianpeng** [comment]
It works on my laptop when I removing Chinese from Chrome->Settings->Language, only remain English.

**Comment by shenxianpeng** [comment]
So I think this PR could be closed.

**Comment by LinuxSuRen** [comment]
Yes. We might need to pass some params to this URL.

The redirection is made from https://github.com/jenkins-infra/jenkins-infra/pull/1314.

**Pull request closed without merging**
