### PR TITLE
update ruby to 2.6

### PR DESCRIPTION
**Pull request by zhaoying818**
### 检查项（Submitter checklist）

- [ ] 已添加 Issue
- [x] 已阅读[翻译规范](https://github.com/jenkinsci/localization-zh-cn-plugin/blob/master/specification.md)
- [ ] [原文地址](https://github.com/jenkins-x/jx-docs/blob/master/sample.md please change me)

### Desired reviewers

@jenkins-infra/chinese-localization-sig

### CODE REVIEW

**Comment by zhaoying818** [comment]
this is not OK! 
Do not Merge!

**Comment by yJunS** [comment]
> this is not OK!
> Do not Merge!

What are the questions? I already try it, it's ok.

**Comment by zhaoying818** [comment]
> 
> 
> > this is not OK!
> > Do not Merge!
> 
> What are the questions? I already try it, it's ok.

https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Fcn.jenkins.io/detail/PR-320/1/pipeline/18

**Comment by yJunS** [comment]
> > > this is not OK!
> > > Do not Merge!
> > 
> > 
> > What are the questions? I already try it, it's ok.
> 
> https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Fcn.jenkins.io/detail/PR-320/1/pipeline/18

I have no problem building locally

**Comment by zhaoying818** [comment]
> 
> 
> > > > this is not OK!
> > > > Do not Merge!
> > > 
> > > 
> > > What are the questions? I already try it, it's ok.
> > 
> > 
> > https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Fcn.jenkins.io/detail/PR-320/1/pipeline/18
> 
> I have no problem building locally

我这边下载速度太慢了，你那边是用的啥代理？

**Comment by zhaoying818** [comment]
> 
> 
> > > > this is not OK!
> > > > Do not Merge!
> > > 
> > > 
> > > What are the questions? I already try it, it's ok.
> > 
> > 
> > https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Fcn.jenkins.io/detail/PR-320/1/pipeline/18
> 
> I have no problem building locally

me too

**Comment by zhaoying818** [comment]
@LinuxSuRen It is OK.
can be merged.

**Review by yJunS — APPROVED** [review]

**Pull request merged**
